### PR TITLE
WEB-4121: Adding support for SVGs

### PR DESCRIPTION
**Pull request by sammyd**
The code to add SVG support is relatively small. It looks for images with `svg` in the alt-text. If it can find an image with the same file name, but with an `.svg` extension instead, then it'll just chuck the contents of the file directly into the HTML.

Most of the rest of the code is trying to bring the styling inline with what we have on the site:

image

This includes showing the SVGs inline:

image

And the ability to toggle between light/dark mode:

image

- @luke-freeman does this look ok for local preview of SVGs?
- @jellodiil seem ok to you?

I need to check that I haven't screwed up the video server too, and then, once this has been merged to staging, maybe we can work out how to get all of combine onto staging so that Luke can finish styling it on carolus?

### CODE REVIEW

**Comment by sammyd** [comment]
Just added a commit that restyles the video index page too:

image

**Review by roelbondoc — APPROVED** [review]
The SVG import code looks good. I didn't go through the rest too thoroughly but seems ok!

**Comment by jellodiil** [comment]
If you are going to do that then there are 2 things, I think
a) books don't care for categories, I think videos should carry on showing the categories. (aka this restyled page will forever flag that it doesn't have categories, and it's one of the things I check for video courses).
b) It doesn't need to show who it is by in the same was a books do? I think it looks just a bit odd.

> Just added a commit that restyles the video index page too:
> 
> image

**Comment by sammyd** [comment]
@jellodiil oh, ok—I didn't actually release that you used the robles preview of the video course. I guess I also didn't realise that the categories used to be on there. I can take a look at adding them. I just updated the HTML to match books so I didn't have to work out what was going on with the CSS.

I can look at adding the categories to this page too—I'll have a crack at finding some more HTML to copy.

**Comment by jellodiil** [comment]
@sammyd Oh, I didn't realise that was just the robles preview of the page rather than  the actual page on carolus. sorry.

**Pull request merged**
